name: ecard_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
#  linear_progress_bar: ^1.1.3
#  flutter_advanced_switch: ^3.1.0
  shared_preferences: ^2.3.5
  provider: ^6.1.2
  google_fonts: ^6.2.1
  http: ^1.3.0
  flutter_vector_icons: ^2.0.0
  font_awesome_flutter: ^10.8.0
  loading_animation_widget: ^1.3.0
  camera: ^0.11.1
  skeletonizer: ^1.4.3
  circle_nav_bar: ^2.2.0
  flutter_ripple: ^0.0.3
  google_maps_flutter: ^2.12.1
  permission_handler: ^12.0.0+1
  google_maps_flutter_web: ^0.5.12
  geolocator: ^9.0.0
  device_preview: ^1.2.0
  flutter_colorpicker: ^1.1.0
  sqflite: ^2.4.1
  flutter_otp_text_field: ^1.5.1+1
  lottie: ^3.3.1
  url_launcher: ^6.3.1
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  jwt_decode: ^0.3.1
  page_transition: any
  path: any
  geocoding: ^4.0.0
  curved_navigation_bar: ^1.0.6
  web_socket_channel: ^3.0.3
  image_picker: ^1.1.2
  photo_manager: ^3.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/anime/no-content.json
    - assets/anime/empty-inbox.json
    - assets/anime/messages.json
    - assets/images/splash-card-image-front.jpg
    - assets/images/splash-card-image-back.jpg
    - assets/anime/

#  fonts:
#    - family: Roboto
#      fonts:
#        - asset: fonts/Roboto-Regular.ttf


